
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gs_money_db_dev
  username: docker
  password: docker
  host: localhost
  port: 5432

test:
  <<: *default
  database: gs_money_db_test
  username: docker
  password: docker
  host: localhost
  port: 5432

production:
  <<: *default
  database: microverse_recipe_app_production
  username: microverse_recipe_app
  password: <%= ENV["MICROVERSE_RECIPE_APP_DATABASE_PASSWORD"] %>
